// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR2LVEY7GcBEEEycIKZDllAl9xUPA740o',
    appId: '1:257317708311:web:f8673d63dffee599917252',
    messagingSenderId: '257317708311',
    projectId: 'flutter-firebase-c7526',
    authDomain: 'flutter-firebase-c7526.firebaseapp.com',
    storageBucket: 'flutter-firebase-c7526.firebasestorage.app',
    measurementId: 'G-RPZD42TXLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASVQma-FMcSttwCn7R1SwzQsohr_05600',
    appId: '1:257317708311:android:e31adc1da1956ba6917252',
    messagingSenderId: '257317708311',
    projectId: 'flutter-firebase-c7526',
    storageBucket: 'flutter-firebase-c7526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCduu6nkgTEBtwfyBo1hLman7tEDxQcWzg',
    appId: '1:257317708311:ios:c96fa1c98d5980ef917252',
    messagingSenderId: '257317708311',
    projectId: 'flutter-firebase-c7526',
    storageBucket: 'flutter-firebase-c7526.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCduu6nkgTEBtwfyBo1hLman7tEDxQcWzg',
    appId: '1:257317708311:ios:c96fa1c98d5980ef917252',
    messagingSenderId: '257317708311',
    projectId: 'flutter-firebase-c7526',
    storageBucket: 'flutter-firebase-c7526.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR2LVEY7GcBEEEycIKZDllAl9xUPA740o',
    appId: '1:257317708311:web:6311ce3a3010ac03917252',
    messagingSenderId: '257317708311',
    projectId: 'flutter-firebase-c7526',
    authDomain: 'flutter-firebase-c7526.firebaseapp.com',
    storageBucket: 'flutter-firebase-c7526.firebasestorage.app',
    measurementId: 'G-8QND07RFR8',
  );
}
